#!/bin/bash
clear
if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ -z "$1" ]; then
	echo "lords mobile: command line information" && exit
fi

lvls='[1-5]'
if ! [[ $2 =~ $lvls ]] ; then
	echo "error: missing or impossible level" 
	echo "useage: lm-cli -qb 4"
	exit
fi

if [ "$1" = -arctic ] || [ "$1" = -flipper ] || [ "$1" = -maf ] || [ "$1" = -marc ] || [ "$1" = -mart ] || [ "$1" = -af ]; then
	monster="arctic flipper"
	level1=("bombin goblin" "petite devil" "sage of storms" "incinerator" "snow queen")
	level2=("incinerator" "bombin goblin" "elementalist" "snow queen" "sage of storms")
	level3=("prima donna" "incinerator" "bombin goblin" "elementalist" "sage of storms")
	level4=("child of light" "prima donna" "incinerator" "elementalist" "sage of storms")
	level5=("child of light" "prima donna" "incinerator" "elementalist" "sage of storms")
elif [ "$1" = -blackwing ] || [ "$1" = -mbw ] || [ "$1" = -mblk ] || [ "$1" = -blkw ] || [ "$1" = -bw ]; then
	monster="blackwing"
	level1=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "tracker")
	level2=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "tracker")
	level3=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "tracker")
	level4=("black crow" "demon slayer" "femme fatale" "rose knight" "death archer")
	level5=("black crow" "demon slayer" "death knight" "prima donna" "death archer")
elif [ "$1" = -bon ] || [ "$1" = -appeti ] || [ "$1" = -mba ] || [ "$1" = -mbon ] || [ "$1" = -ba ]; then
	monster="bon appeti"
	level1=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "tracker")
	level2=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "tracker")
	level3=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "tracker")
	level4=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "tracker")
	level5=("black crow" "demon slayer" "scarlet bolt" "death knight" "trickster")
elif [ "$1" = -cottageroar ] || [ "$1" = -mcot ] || [ "$1" = -mcott ] || [ "$1" = -mcr ] || [ "$1" = -cr ]; then
	monster="cottageroar"
	level1=("black crow" "shade" "demon slayer" "tracker" "scarlet bolt")
	level2=("black crow" "shade" "demon slayer" "tracker" "scarlet bolt")
	level3=("black crow" "tracker" "demon slayer" "trickster" "scarlet bolt")
	level4=("black crow" "tracker" "demon slayer" "trickster" "scarlet bolt")
	level5=("black crow" "death knight" "demon slayer" "boommeister" "scarlet bolt")
elif [ "$1" = -frostwing ] || [ "$1" = -mfw ] || [ "$1" = -mfro ] || [ "$1" = -fro ] || [ "$1" = -frost ] || [ "$1" = -fw ]; then
	monster="frosting"
	level1=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "death archer")
	level2=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "death archer")
	level3=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "death archer")
	level4=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "death archer")
	level5=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "death archer")
elif [ "$1" = -gargantua ] || [ "$1" = -mgar ] || [ "$1" = -mgarg ] || [ "$1" = -garg ] || [ "$1" = -gar ]; then
	monster="gargantua"
	level1=("child of light" "incinerator" "elementalist" "snow queen" "bombin goblin")
	level2=("child of light" "incinerator" "elementalist" "snow queen" "bombin goblin")
	level3=("child of light" "incinerator" "elementalist" "snow queen" "bombin goblin")
	level4=("child of light" "incinerator" "elementalist" "petite devil" "dream witch")
	level5=("child of light" "incinerator" "elementalist" "snow queen" "prima donna")
elif [ "$1" = -gawrilla ] || [ "$1" = -tusker ] || [ "$1" = -mtus ] || [ "$1" = -mtusk ] || [ "$1" = -tusk ] || [ "$1" = -mgaw ] || [ "$1" = -mgawr ]; then
	monster="tasker"
	level1=("incinerator" "bombin goblin" "elementalist" "snow queen" "sage of storms")
	level2=("incinerator" "bombin goblin" "elementalist" "snow queen" "sage of storms")
	level3=("prima donna" "incinerator" "bombin goblin" "elementalist" "sage of storms")
	level4=("child of light" "prima donna" "incinerator" "elementalist" "sage of storms")
	level5=("child of light" "prima donna" "incinerator" "elementalist" "sage of storms")
elif [ "$1" = -grim ] || [ "$1" = -reaper ] || [ "$1" = -mgri ] || [ "$1" = -mgr ] || [ "$1" = -gr ]; then
	monster="grim reaper"
	level1=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "death archer")
	level2=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "death archer")
	level3=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "death archer")
	level4=("black crow" "demon slayer" "scarlet bolt" "death knight" "trickster")
	level5=("black crow" "demon slayer" "prima donna" "death knight" "death archer")
elif [ "$1" = -gryphon ] || [ "$1" = -mgry ] || [ "$1" = -grif ]; then
	monster="gryphon"
	level1=("black crow" "demon slayer" "scarlet bolt" "tracker" "femme fatale")
	level2=("black crow" "demon slayer" "scarlet bolt" "tracker" "femme fatale")
	level3=("black crow" "demon slayer" "scarlet bolt" "tracker" "femme fatale")
	level4=("black crow" "demon slayer" "scarlet bolt" "tracker" "night raven")
	level5=("black crow" "demon slayer" "scarlet bolt" "tracker" "night raven")
elif [ "$1" = -hardrox ] || [ "$1" = -mhar ] || [ "$1" = -mhr ] || [ "$1" = -rox ] || [ "$1" = -hard ] || [ "$1" = -hr ]; then
	monster="hardrox"
	level1=("sage of storms" "incinerator" "elementalist" "snow queen" "bombin goblin")
	level2=("sage of storms" "incinerator" "elementalist" "snow queen" "bombin goblin")
	level3=("sage of storms" "incinerator" "elementalist" "snow queen" "bombin goblin")
	level4=("prima donna" "incinerator" "elementalist" "snow queen" "bombin goblin")
	level5=("prima donna" "incinerator" "elementalist" "snow queen" "child of light")
elif [ "$1" = -hell ] || [ "$1" = -drider ] || [ "$1" = -mhel ] || [ "$1" = -mhd ] || [ "$1" = -hd ]; then
	monster="hell driver"
	level1=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "tracker")
	level2=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "tracker")
	level3=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "tracker")
	level4=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "death archer")
	level5=("black crow" "demon slayer" "death knight" "death archer" "tracker")
elif [ "$1" = -hootclaw ] || [ "$1" = -mhoo ] || [ "$1" = -mhc ] || [ "$1" = -hc ] || [ "$1" = -hoot ]; then
	monster="hootclaw"
	level1=("sage of storms" "incinerator" "elementalist" "snow queen" "bombin goblin")
	level2=("sage of storms" "incinerator" "elementalist" "snow queen" "bombin goblin")
	level3=("prima donna" "incinerator" "elementalist" "snow queen" "bombin goblin")
	level4=("prima donna" "incinerator" "elementalist" "snow queen" "bombin goblin")
	level5=("prima donna" "incinerator" "elementalist" "snow queen" "child of light")
elif [ "$1" = -jade ] || [ "$1" = -wyrm ] || [ "$1" = -mjad ] || [ "$1" = -mjw ]  || [ "$1" = -jw ] || [ "$1" = -worm ]; then
	monster="jade warm"
	level1=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level2=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level3=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level4=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level5=("sage of storms" "incinerator" "elementalist" "prima donna" "child of light")
elif [ "$1" = -mecha ] || [ "$1" = -trojan ] || [ "$1" = -mmec ] || [ "$1" = -mmt ] || [ "$1" = -mt ]; then
	monster="mecha trojan"
	level1=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level2=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level3=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level4=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level5=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
elif [ "$1" = -mega ] || [ "$1" = -maggot ] || [ "$1" = -mmeg ] || [ "$1" = -mmm ] || [ "$1" = -magg ] || [ "$1" = -mm ]; then
	monster="mega maggot"
	level1=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level2=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level3=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level4=("sage of storms" "incinerator" "elementalist" "prima donna" "bombin goblin")
	level5=("sage of storms" "incinerator" "elementalist" "prima donna" "child of light")
elif [ "$1" = -necrosis ] || [ "$1" = -mnec ] || [ "$1" = -dead ] || [ "$1" = -zombie ] || [ "$1" = -mzom ] || [ "$1" = -mzomb ] || [ "$1" = -neck ]; then
	monster="necrosis"
	level1=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level2=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level3=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level4=("incinerator" "elementalist" "bombin goblin prima donna" "child of light")
	level5=("sage of storms" "incinerator" "elementalist" "prima donna" "child of light")
elif [ "$1" = -noceros ] || [ "$1" = -mnor ] || [ "$1" = -noce ] || [ "$1" = -rhino ]; then
	monster="noceros"
	level1=("witch doll" "incinerator" "elementalist" "petite devil" "dream witch")
	level2=("witch doll" "incinerator" "elementalist" "petite devil" "dream witch")
	level3=("witch doll" "incinerator" "elementalist" "petite devil" "dream witch")
	level4=("sage of storms" "incinerator" "elementalist" "prima donna" "bombin goblin")
	level5=("sage of storms" "incinerator" "elementalist" "prima donna" "child of light")
elif [ "$1" = -queen ] || [ "$1" = -bee ] || [ "$1" = -mque ] || [ "$1" = -mqb ] || [ "$1" = -qb ]; then
	monster="queen bee"
	level1=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "tracker")
	level2=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "tracker")
	level3=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "tracker")
	level4=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "tracker")
	level5=("black crow" "demon slayer" "scarlet bolt" "death archer" "trickster")
elif [ "$1" = -saberfang ] || [ "$1" = -msab ] || [ "$1" = -msf ] || [ "$1" = -saber ] || [ "$1" = -fang ] || [ "$1" = -sf ]; then
	monster="saberfang"
	level1=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level2=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level3=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level4=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level5=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
elif [ "$1" = -serpent ] || [ "$1" = -gladiator ] || [ "$1" = -mser ] || [ "$1" = -serp ] || [ "$1" = -msg ] || [ "$1" = -glad ] || [ "$1" = -sg ]; then
	monster="serpent gladiator"
	level1=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level2=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level3=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level4=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level5=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
elif [ "$1" = -snow ] || [ "$1" = -beast ] || [ "$1" = -msno ] || [ "$1" = -msb ] || [ "$1" = -sb ]; then
	monster="snow beast"
	level1=("black crow" "demon slayer" "scarlet bolt" "tracker" "trickster")
	level2=("black crow" "demon slayer" "scarlet bolt" "tracker" "trickster")
	level3=("black crow" "demon slayer" "scarlet bolt" "tracker" "trickster")
	level4=("black crow" "demon slayer" "scarlet bolt" "tracker" "trickster")
	level5=("black crow" "demon slayer" "scarlet bolt" "death archer" "trickster")
elif [ "$1" = -terrorthorn ] || [ "$1" = -mter ] || [ "$1" = -terror ] || [ "$1" = -thorn ] || [ "$1" = -mthorn ]; then
	monster="terrorthorn"
	level1=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "shade")
	level2=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "shade")
	level3=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "shade")
	level4=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "shade")
	level5=("black crow" "demon slayer" "femme fatale" "scarlet bolt" "shade")
elif [ "$1" = -tidal ] || [ "$1" = -titan ] || [ "$1" = -mtid ] || [ "$1" = -mtt ] || [ "$1" = -tt ]; then
	monster="tidal titan"
	level1=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level2=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level3=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level4=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
	level5=("storm fox" "incinerator" "elementalist" "petite devil" "dream witch")
elif [ "$1" = -voodoo ] || [ "$1" = -shaman ] || [ "$1" = -mvoo ] || [ "$1" = -mvs ] || [ "$1" = -vs ] || [ "$1" = -vd ] || [ "$1" = -vds ]; then
	monster="voodoo shaman"
	level1=("black crow" "demon slayer" "death archer" "tracker" "trickster")
	level2=("black crow" "demon slayer" "death archer" "tracker" "trickster")
	level3=("black crow" "demon slayer" "death archer" "tracker" "trickster")
	level4=("black crow" "demon slayer" "death archer" "tracker" "trickster")
	level5=("black crow" "demon slayer" "rose knight" "tracker" "trickster")
else
	echo "error: unknown input" && exit
fi

echo "$monster (lv$2)" && echo

if [ "$2" = 1 ]; then
	echo ${level1[0]}
	echo ${level1[1]}
	echo ${level1[2]}
	echo ${level1[3]}
	echo ${level1[4]}
elif [ "$2" = 2 ]; then
	echo ${level2[0]}
	echo ${level2[1]}
	echo ${level2[2]}
	echo ${level2[3]}
	echo ${level2[4]}
elif [ "$2" = 3 ]; then
	echo ${level3[0]}
	echo ${level3[1]}
	echo ${level3[2]}
	echo ${level3[3]}
	echo ${level3[4]}
elif [ "$2" = 4 ]; then
	echo ${level4[0]}
	echo ${level4[1]}
	echo ${level4[2]}
	echo ${level4[3]}
	echo ${level4[4]}
elif [ "$2" = 5 ]; then
	echo ${level5[0]}
	echo ${level5[1]}
	echo ${level5[2]}
	echo ${level5[3]}
	echo ${level5[4]}
fi
